kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc-demo
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # 申请的资源大小
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: my-first-ubuntu-tf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: my-ubuntu-tf
  template:
    metadata:
      labels:
        name: my-ubuntu-tf
    spec:
      hostNetwork: true
      hostIPC: true
      containers:
      - name: orion-client-hvd
        image: 172.16.112.173:30006/library/ubuntu-tensorflow:2.3.0  # 可自行更改镜像和版本
        command: ["bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        resources:
          limits:
            cpu: 10 # 最大CPU 数目：10个cpu内核
            memory: 40Gi # 最大内存数目: 40GB
            virtaitech.com/gpu: 1  # 最大GPU数目
          requests:
            cpu: 10 # 最小需要的CPU数目 （如果目前资源不够，就放弃启动）
            memory: 40Gi # 最小需要申请的内存的数目（如果目前资源不够，就放弃启动）
            virtaitech.com/gpu: 1  # 最小需要的GPU数目
        env:
          - name : ORION_GMEM
            value : "10000"  # 每张显卡的显存，单位为M
          - name : ORION_RATIO
            value : "100"
          - name: ORION_VGPU
            value: "1"
          - name: ORION_RESERVED
            value: "0"
          - name: ORION_CROSS_NODE
            value: "1"
          - name: ORION_GROUP_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
        volumeMounts:
        - name: my-local-disk-1
          mountPath: /mnt/data1
        - name: my-local-disk-2
          mountPath: /mnt/data2
        - name: my-pvc
          mountPath: /pvc
      volumes:
        - name: my-local-disk-1
          hostPath:
            path: /data  # 两块物理盘，/data 大小3.7T，/data2 大小3.0T
        - name: my-local-disk-2
          hostPath:
            path: /data2
        - name: my-pvc
          persistentVolumeClaim:
            claimName: my-pvc-demo