kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc-demo
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # 申请的资源大小
