apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: my-runtime-torch
#  namespace: orion
spec:
  replicas: 1
  selector:
    matchLabels:
      name: my-runtime-torch
  template:
    metadata:
      labels:
        name: my-runtime-torch
    spec:
      hostNetwork: true
      schedulerName: orion-scheduler     #使用 orion-scheduler 的gpu调度器      
      hostIPC: true
      containers:
      - name: my-runtime-torch
        #image: hub.virtaitech.com/orionx/my-client:2.8.2_torch1.7.1-cu10.2-cudnn7-py3.6-ubuntu18.04-mnist-dist
        image: 172.16.112.220:30006/library/orion-client:2.8.2_torch1.7.1-cu10.2-cudnn7-py3.6-ubuntu18.04-mnist-dist
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args: ["while true; do sleep 30; done;"]
        resources:
          requests:
            cpu: 4 # 最小CPU
            memory: 10Gi # 最大内存          
            virtaitech.com/gpu: 1    #申请vgpu数量
          limits:
            cpu: 4 # 最大需要的CPU数目 （如果目前资源不够，就放弃启动）
            memory: 11Gi # 最小需要申请的内存的数目（如果目前资源不够，就放弃启动）          
            virtaitech.com/gpu: 1
        env:
          - name : ORION_GMEM  
            value : "10000"   # 每张显卡的显存，单位为M，最好使用10G
          - name : ORION_RATIO
            value : "100"
          - name: ORION_VGPU
            value: "1"
          - name: ORION_RESERVED  #VGPU的共享和独享模式选择，默认0。 0是非资源预留模式，1，即进行资源预留
            value: "0"
          - name: ORION_CROSS_NODE  #运算是否调用远程VGPU，默认1.  0是不可以调用远程VGPU，1是可以调用远程VGPU。
            value: "1"
          - name: ORION_SCHEDULE_RULE
            value: "local-first"   #优先进行本地调用
          - name : ORION_GROUP_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          #以下添加内容valueFrom       
          - name: ORION_K8S_POD_NAME   #vGPU资源使用率相关，缺省 pod名称
            valueFrom:
             fieldRef:
               fieldPath: metadata.name
          - name: ORION_K8S_POD_UID   #vGPU 资源使用率相关，缺省 pod uid
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: ORION_K8S_POD_NS
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
